// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";

import { PlasmicHomepage } from "../components/plasmic/a_d/PlasmicHomepage";
import { useRouter } from "next/router";
import HomeMobile from "@/components/HomeMobile";
import FaleConoscoMobile from "@/components/FaleConoscoMobile";
import BackgroundDesktop from "@/components/BackgroundDesktop";
import HomeDesktopPage1 from "@/components/HomeDesktopPage1";
import HomeDesktopPage2 from "@/components/HomeDesktopPage2";
import HomeDesktopPage3 from "@/components/HomeDesktopPage3";

function Homepage() {
  return (
    <PageParamsProvider__
      route={useRouter()?.pathname}
      params={useRouter()?.query}
      query={useRouter()?.query}
    >
      <PlasmicHomepage
        mobile={
          <>
            <HomeMobile />
            <div
              style={{
                position: "fixed",
                right: 10,
                bottom: 10,
              }}
            >
              <FaleConoscoMobile />
            </div>
          </>
        }
        desktop={
          <>
            <div
              style={{
                position: "fixed",
                width: "100vw",
                height: "100vh",
              }}
            >
              <BackgroundDesktop />
            </div>
            <div>
              <div
                style={{
                  height: "100vh",
                }}
              >
                <HomeDesktopPage1 />
              </div>
              <div
                style={{
                  height: "100vh",
                }}
              >
                <HomeDesktopPage2 />
              </div>
              <div
                style={{
                  height: "100vh",
                }}
              >
                <HomeDesktopPage3 />
              </div>
            </div>
          </>
        }
      />
    </PageParamsProvider__>
  );
}

export default Homepage;
