// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";

import { PlasmicLogin } from "../components/plasmic/a_d/PlasmicLogin";
import { useRouter } from "next/router";

function Login() {
  const [name, setName] = React.useState("");
  const [password, setPassword] = React.useState("");
  const [error, setError] = React.useState(false);
  const router = useRouter();

  const handleLogin = () => {
    if (password !== process.env.NEXT_PUBLIC_ADMIN_PASSWORD) {
      setError(true);
      return;
    }
    if (name.length < 3) {
      setError(true);
      return;
    }
    localStorage.setItem("isv-admin", name);
    router.push("/");
  }

  return (
    <PageParamsProvider__
      route={useRouter()?.pathname}
      params={useRouter()?.query}
      query={useRouter()?.query}
    >
      <PlasmicLogin
        incorrect={error}
        textInput={{
          value: name,
          onChange: (e) => setName(e.target.value)
        }}
        textInput2={{
          value: password,
          onChange: (e) => setPassword(e.target.value)
        }}
        button={{
          onClick: handleLogin
        }}
      />
    </PageParamsProvider__>
  );
}

export default Login;
