// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";

import { PlasmicLogin } from "../components/plasmic/a_d_2/PlasmicLogin";
import { useRouter } from "next/router";

function Login() {
  const [error, setError] = React.useState(false);
  const router = useRouter();

  const handleLogin = (name: string, password: string) => {
    if (password !== process.env.NEXT_PUBLIC_ADMIN_PASSWORD) {
      setError(true);
      return;
    }
    if (name.length < 3) {
      setError(true);
      return;
    }
    localStorage.setItem("isv-admin", name);
    router.push("/");
  };
  return (
    <PageParamsProvider__
      route={useRouter()?.pathname}
      params={useRouter()?.query}
      query={useRouter()?.query}
    >
      <PlasmicLogin
        error={error ? "Senha invalida" : undefined}
        onLogin={handleLogin as any}
      />
    </PageParamsProvider__>
  );
}

export default Login;
