// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";

import { PlasmicStatus } from "../components/plasmic/a_d/PlasmicStatus";
import { useRouter } from "next/router";
import {
  useMutablePlasmicQueryData,
  usePlasmicQueryData,
} from "@plasmicapp/react-web/lib/query";
import { supabase } from "@/components/supabase/supabase";
import { ColorRing } from "react-loader-spinner";

function Status() {
  const { data: inscritos, isLoading: isLoadingInscritos } =
    useMutablePlasmicQueryData("inscritos", async () => {
      const { data: inscritos, error: err1 } = await supabase
        .from("inscritos_ad")
        .select(
          `
            *,
            payments_ad (id, paid, lote)
          `
        );
      if (!inscritos) {
        throw new Error(err1?.message ?? "Unknown error");
      }
      const paid = [];
      for (const inscricao of inscritos) {
        console.log("xqdl", inscricao);
        const newLine = {
          id: inscricao.id,
          fullName: inscricao.name,
          cpf: inscricao.cpf,
          telefone: inscricao.telefone,
          email: inscricao.email,
          adulto: inscricao.qtt,
          kids: inscricao.kids,
          status: inscricao.payments?.[0]?.paid ? "PAGO" : "AGUARDANDO",
        };
        console.log("xqdl2", newLine);

        if (inscricao.payments_ad?.find((p: any) => p.paid)) {
          paid.push(newLine);
        }
      }
      return paid;
    });

  const { data: checkin, isLoading: isLoadingCheckIn } =
    useMutablePlasmicQueryData(
      "checkin",
      async () => {
        const { data, error } = await supabase.from("checkin").select("*");

        if (!data) {
          throw new Error(error.message ?? "Unknown error");
        }
        return data;
      },
      { refreshInterval: 1000 }
    );

  const count = {
    kidsIn: 0,
    kidsOut: 0,
    adultosIn: 0,
    adultosOut: 0,
  };

  if (inscritos && checkin) {
    for (const inscrito of inscritos) {
      for (let i = 0; i < inscrito.adulto; i++) {
        const row = checkin.find(
          (r) => r.inscricao_id === inscrito.id && r.inscricao_number === i
        );
        if (row) {
          count.adultosIn++;
        } else {
          count.adultosOut++;
        }
      }
      for (let i = 0; i < inscrito.kids; i++) {
        const row = checkin.find(
          (r) =>
            r.inscricao_id === inscrito.id &&
            r.inscricao_number === i + inscrito.adulto
        );
        if (row) {
          count.kidsIn++;
        } else {
          count.kidsOut++;
        }
      }
    }
  }

  console.log('dale', { count, inscritos, checkin })

  return (
    <PageParamsProvider__
      route={useRouter()?.pathname}
      params={useRouter()?.query}
      query={useRouter()?.query}
    >
      <PlasmicStatus
        vipIn={count.adultosIn || "0"}
        vipOut={count.adultosOut || "0"}
        geralIn={count.kidsIn || "0"}
        geralOut={count.kidsOut || "0"}
        loading={!inscritos || !checkin}
        children={
          <ColorRing
            visible={true}
            height="300"
            width="300"
            ariaLabel="color-ring-loading"
            wrapperStyle={{}}
            wrapperClass="color-ring-wrapper"
            colors={["blue", "blue", "blue", "blue", "blue"]}
          />
        }
      />
    </PageParamsProvider__>
  );
}

export default Status;
