// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";

import { PlasmicHomepage } from "../components/plasmic/a_d_2/PlasmicHomepage";
import { useRouter } from "next/router";

import { supabase } from "@/components/supabase/supabase";
import { nanoid } from "nanoid";
import validator from "email-validator";

function Homepage() {
  const [isLoading, setIsLoading] = React.useState(false);
  const [error, setError] = React.useState("");
  const router = useRouter();

  const handleContinue = async ({ name, cpf, email, qtt }: any) => {
    setError("");
    setIsLoading(true);

    if (!validator.validate(email)) {
      setError("Email invalido");
      setIsLoading(false);
      return;
    }

    try {
      const mercadoPagoId = nanoid() + nanoid();

      const response = await fetch(
        `${process.env.NEXT_PUBLIC_ENDPOINT}/api/mercadopago/preference`,
        {
          method: "POST",
          body: JSON.stringify({
            name: name,
            email: email,
            id: mercadoPagoId,
            items: [
              {
                id: 0,
                title: "Ingressos A&D",
                description: "Ingressos para A&D 2025",
                quantity: qtt,
                currency_id: "BRL",
                unit_price: 0.02
              },
            ],
          }),
        }
      );

      const responseJson = await response.json();

      const newRow = await supabase
        .from("inscritos_ad")
        .insert({
          name,
          cpf,
          email,
          mercadoPagoId,
          mercadoPagoLink: responseJson.response.init_point,
          qtt,
        })
        .select();

      if (newRow.error || newRow.data.length !== 1) {
        throw new Error(newRow.error?.message ?? "Unknown error");
      }

      router.push(responseJson.response.init_point);
    } catch (err) {
      setIsLoading(false);
      setError((err as any).message);
    }
  };

  return (
    <PageParamsProvider__
      route={useRouter()?.pathname}
      params={useRouter()?.query}
      query={useRouter()?.query}
    >
      <PlasmicHomepage
        onContinue={handleContinue}
        isLoading={isLoading}
        error={error}
        price={0.02}
      />
    </PageParamsProvider__>
  );
}

export default Homepage;
