/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vVD1sTFSmdjjS6SHX4G6gi
// Component: zddfBJHQWGjg

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Loading from "../../Loading"; // plasmic-import: jjiZWn6Rmy6Y/component
import Button from "../../Button"; // plasmic-import: Td7P8G5TJYZK/component
import TextField from "../../TextField"; // plasmic-import: dcswTQKiNiea/component

import { useScreenVariants as useScreenVariantsht85E1RMwQbV } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: ht85e1RMwQbV/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_color_tokens_css from "../color_tokens/plasmic.module.css"; // plasmic-import: cUBNGVYNKSb57j9eXqwvXN/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: vVD1sTFSmdjjS6SHX4G6gi/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: zddfBJHQWGjg/css

import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: D6J4d5giOwp9/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: vr9vhqSbbQFF/icon

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {
  onContinue?: (data: any) => void;
  isLoading?: boolean;
  error?: string;
  price?: number;
};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>(
  "onContinue",
  "isLoading",
  "error",
  "price"
);

export type PlasmicHomepage__OverridesType = {
  root?: Flex__<"div">;
  loading?: Flex__<typeof Loading>;
  h3?: Flex__<"h3">;
  span?: Flex__<"span">;
  link?: Flex__<"a"> & Partial<LinkProps>;
  name?: Flex__<typeof TextField>;
  cpf?: Flex__<typeof TextField>;
  email?: Flex__<typeof TextField>;
};

export interface DefaultHomepageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          isLoading: false,
          price: 10
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "name.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "cpf.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "email.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "qtt",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 0
      },
      {
        path: "kids",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 0
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsht85E1RMwQbV()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_color_tokens_css.plasmic_tokens,
            sty.root
          )}
        >
          {(() => {
            try {
              return $props.isLoading;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return true;
              }
              throw e;
            }
          })() ? (
            <Loading
              data-plasmic-name={"loading"}
              data-plasmic-override={overrides.loading}
              className={classNames("__wab_instance", sty.loading)}
            />
          ) : null}
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__fIty)}
          >
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__zNzev)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: "/plasmic/a_d_2/images/cover.jpg",
                fullWidth: 1080,
                fullHeight: 1350,
                aspectRatio: undefined
              }}
            />
          </Stack__>
          <div className={classNames(projectcss.all, sty.freeBox__nk1D)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__zUkYq
              )}
            >
              <React.Fragment>
                <React.Fragment>{""}</React.Fragment>
                {
                  <h3
                    data-plasmic-name={"h3"}
                    data-plasmic-override={overrides.h3}
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.__wab_text,
                      sty.h3
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"ATEN\u00c7\u00c3O"}
                      </span>
                    </React.Fragment>
                  </h3>
                }
                <React.Fragment>
                  {"\nO evento acontecer\u00e1 nos dias 1 e 2 de agosto!\n\n"}
                </React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"Valor do ingresso:"}
                </span>
                <React.Fragment>{" R$ "}</React.Fragment>
                {
                  <span
                    data-plasmic-name={"span"}
                    data-plasmic-override={overrides.span}
                    className={classNames(
                      projectcss.all,
                      projectcss.span,
                      projectcss.__wab_text,
                      projectcss.plasmic_default__inline,
                      sty.span
                    )}
                  >
                    <React.Fragment>
                      {(() => {
                        try {
                          return $props.price.toFixed(2).replace(".", ",");
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return "10,00";
                          }
                          throw e;
                        }
                      })()}
                    </React.Fragment>
                  </span>
                }
                <React.Fragment>{"\n\n"}</React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"Importante:"}
                </span>
                <React.Fragment>
                  {" A partir de 3 anos, ser\u00e1 cobrado ingresso"}
                </React.Fragment>
              </React.Fragment>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__nBJfo)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__gFVl
              )}
            >
              {"Ficou com alguma d\u00favida?"}
            </div>
            <PlasmicLink__
              data-plasmic-name={"link"}
              data-plasmic-override={overrides.link}
              className={classNames(projectcss.all, projectcss.a, sty.link)}
              component={Link}
              href={"https://wa.me/+5513991259404"}
              platform={"nextjs"}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__xhaX0)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"100px"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/a_d_2/images/whatsapp.png",
                  fullWidth: 600,
                  fullHeight: 383,
                  aspectRatio: undefined
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__whaMc
                )}
              >
                {"Fale conosco"}
              </div>
            </PlasmicLink__>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__jwcTo)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__j6TD
              )}
            >
              {"Inscri\u00e7\u00e3o"}
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__ls8XB)}>
            <div className={classNames(projectcss.all, sty.freeBox__v5M45)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__dbwhl
                )}
              >
                {"Adultos"}
              </div>
            </div>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__neSsn)}
            >
              <Button
                className={classNames("__wab_instance", sty.button__dQvx8)}
                color={"neutral"}
                disabled={(() => {
                  try {
                    return $state.qtt === 0;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return undefined;
                    }
                    throw e;
                  }
                })()}
                label={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dcnPv
                    )}
                  >
                    {"-"}
                  </div>
                }
                onClick={async event => {
                  const $steps = {};

                  $steps["updateQtt"] = true
                    ? (() => {
                        const actionArgs = {
                          variable: {
                            objRoot: $state,
                            variablePath: ["qtt"]
                          },
                          operation: 3
                        };
                        return (({
                          variable,
                          value,
                          startIndex,
                          deleteCount
                        }) => {
                          if (!variable) {
                            return;
                          }
                          const { objRoot, variablePath } = variable;

                          const oldValue = $stateGet(objRoot, variablePath);
                          $stateSet(objRoot, variablePath, oldValue - 1);
                          return oldValue - 1;
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["updateQtt"] != null &&
                    typeof $steps["updateQtt"] === "object" &&
                    typeof $steps["updateQtt"].then === "function"
                  ) {
                    $steps["updateQtt"] = await $steps["updateQtt"];
                  }
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qJdJl
                )}
              >
                <React.Fragment>
                  {(() => {
                    try {
                      return $state.qtt;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return "0";
                      }
                      throw e;
                    }
                  })()}
                </React.Fragment>
              </div>
              <Button
                className={classNames("__wab_instance", sty.button__me4QD)}
                color={"neutral"}
                label={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mLy1
                    )}
                  >
                    {"+"}
                  </div>
                }
                onClick={async event => {
                  const $steps = {};

                  $steps["updateQtt"] = true
                    ? (() => {
                        const actionArgs = {
                          variable: {
                            objRoot: $state,
                            variablePath: ["qtt"]
                          },
                          operation: 2
                        };
                        return (({
                          variable,
                          value,
                          startIndex,
                          deleteCount
                        }) => {
                          if (!variable) {
                            return;
                          }
                          const { objRoot, variablePath } = variable;

                          const oldValue = $stateGet(objRoot, variablePath);
                          $stateSet(objRoot, variablePath, oldValue + 1);
                          return oldValue + 1;
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["updateQtt"] != null &&
                    typeof $steps["updateQtt"] === "object" &&
                    typeof $steps["updateQtt"].then === "function"
                  ) {
                    $steps["updateQtt"] = await $steps["updateQtt"];
                  }
                }}
              />
            </Stack__>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__naqCr)}>
            <div className={classNames(projectcss.all, sty.freeBox__zwcWi)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__bg1U
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "Crian\u00e7as\n(3 a 10 anos)"
                  : "Crian\u00e7as (3 a 10 anos)"}
              </div>
            </div>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__sUo4H)}
            >
              <Button
                className={classNames("__wab_instance", sty.button__fvZ4P)}
                color={"neutral"}
                disabled={(() => {
                  try {
                    return $state.kids === 0;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return undefined;
                    }
                    throw e;
                  }
                })()}
                label={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__b6Vo
                    )}
                  >
                    {"-"}
                  </div>
                }
                onClick={async event => {
                  const $steps = {};

                  $steps["updateKids"] = true
                    ? (() => {
                        const actionArgs = {
                          variable: {
                            objRoot: $state,
                            variablePath: ["kids"]
                          },
                          operation: 3
                        };
                        return (({
                          variable,
                          value,
                          startIndex,
                          deleteCount
                        }) => {
                          if (!variable) {
                            return;
                          }
                          const { objRoot, variablePath } = variable;

                          const oldValue = $stateGet(objRoot, variablePath);
                          $stateSet(objRoot, variablePath, oldValue - 1);
                          return oldValue - 1;
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["updateKids"] != null &&
                    typeof $steps["updateKids"] === "object" &&
                    typeof $steps["updateKids"].then === "function"
                  ) {
                    $steps["updateKids"] = await $steps["updateKids"];
                  }
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___8R3Wr
                )}
              >
                <React.Fragment>
                  {(() => {
                    try {
                      return $state.kids;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return "0";
                      }
                      throw e;
                    }
                  })()}
                </React.Fragment>
              </div>
              <Button
                className={classNames("__wab_instance", sty.button__lBzRx)}
                color={"neutral"}
                label={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__u49Wu
                    )}
                  >
                    {"+"}
                  </div>
                }
                onClick={async event => {
                  const $steps = {};

                  $steps["updateKids"] = true
                    ? (() => {
                        const actionArgs = {
                          variable: {
                            objRoot: $state,
                            variablePath: ["kids"]
                          },
                          operation: 2
                        };
                        return (({
                          variable,
                          value,
                          startIndex,
                          deleteCount
                        }) => {
                          if (!variable) {
                            return;
                          }
                          const { objRoot, variablePath } = variable;

                          const oldValue = $stateGet(objRoot, variablePath);
                          $stateSet(objRoot, variablePath, oldValue + 1);
                          return oldValue + 1;
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["updateKids"] != null &&
                    typeof $steps["updateKids"] === "object" &&
                    typeof $steps["updateKids"].then === "function"
                  ) {
                    $steps["updateKids"] = await $steps["updateKids"];
                  }
                }}
              />
            </Stack__>
          </div>
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__j2Yat)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__c2Nn)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__uFy6C
                )}
              >
                <React.Fragment>
                  {(() => {
                    try {
                      return $props.error;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return "Dados inv\u00e1lidos";
                      }
                      throw e;
                    }
                  })()}
                </React.Fragment>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__thJQv)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__kCYjK
                  )}
                >
                  {"Nome completo"}
                </div>
                <TextField
                  data-plasmic-name={"name"}
                  data-plasmic-override={overrides.name}
                  className={classNames("__wab_instance", sty.name)}
                  onChange={async (...eventArgs: any) => {
                    generateStateOnChangeProp($state, ["name", "value"]).apply(
                      null,
                      eventArgs
                    );

                    if (
                      eventArgs.length > 1 &&
                      eventArgs[1] &&
                      eventArgs[1]._plasmic_state_init_
                    ) {
                      return;
                    }
                  }}
                  showLabel={false}
                  value={generateStateValueProp($state, ["name", "value"])}
                />
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__r7Hy2)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wUcQg
                  )}
                >
                  {"CPF"}
                </div>
                <TextField
                  data-plasmic-name={"cpf"}
                  data-plasmic-override={overrides.cpf}
                  className={classNames("__wab_instance", sty.cpf)}
                  onChange={async (...eventArgs: any) => {
                    generateStateOnChangeProp($state, ["cpf", "value"]).apply(
                      null,
                      eventArgs
                    );

                    if (
                      eventArgs.length > 1 &&
                      eventArgs[1] &&
                      eventArgs[1]._plasmic_state_init_
                    ) {
                      return;
                    }
                  }}
                  showLabel={false}
                  value={generateStateValueProp($state, ["cpf", "value"])}
                />
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__fK9MM)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ebwbm
                  )}
                >
                  {"Email"}
                </div>
                <TextField
                  data-plasmic-name={"email"}
                  data-plasmic-override={overrides.email}
                  className={classNames("__wab_instance", sty.email)}
                  onChange={async (...eventArgs: any) => {
                    generateStateOnChangeProp($state, ["email", "value"]).apply(
                      null,
                      eventArgs
                    );

                    if (
                      eventArgs.length > 1 &&
                      eventArgs[1] &&
                      eventArgs[1]._plasmic_state_init_
                    ) {
                      return;
                    }
                  }}
                  showLabel={false}
                  value={generateStateValueProp($state, ["email", "value"])}
                />
              </div>
            </Stack__>
            <div className={classNames(projectcss.all, sty.freeBox__mQuus)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xynvM
                )}
              >
                <React.Fragment>
                  {(() => {
                    try {
                      return `Total: R$ ${(
                        ($state.qtt + $state.kids) *
                        $props.price
                      )
                        .toFixed(2)
                        .replace(".", ",")}`;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return "Total: R$ 0,00";
                      }
                      throw e;
                    }
                  })()}
                </React.Fragment>
              </div>
            </div>
            <Button
              className={classNames("__wab_instance", sty.button__tw0Y9)}
              color={"neutral"}
              disabled={(() => {
                try {
                  return (
                    $props.isLoading ||
                    !$state.cpf.value ||
                    !$state.email.value ||
                    !$state.name.value ||
                    $state.qtt + $state.kids === 0
                  );
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return undefined;
                  }
                  throw e;
                }
              })()}
              label={
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__h676M
                  )}
                >
                  {"Continuar"}
                </div>
              }
              onClick={async event => {
                const $steps = {};

                $steps["runOnContinue"] = true
                  ? (() => {
                      const actionArgs = {
                        eventRef: $props["onContinue"],
                        args: [
                          (() => {
                            try {
                              return {
                                name: $state.name.value,
                                cpf: $state.cpf.value,
                                email: $state.email.value,
                                qtt: $state.qtt,
                                kids: $state.kids
                              };
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()
                        ]
                      };
                      return (({ eventRef, args }) => {
                        return eventRef?.(...(args ?? []));
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["runOnContinue"] != null &&
                  typeof $steps["runOnContinue"] === "object" &&
                  typeof $steps["runOnContinue"].then === "function"
                ) {
                  $steps["runOnContinue"] = await $steps["runOnContinue"];
                }
              }}
              size={"extraLarge"}
            />
          </Stack__>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "loading", "h3", "span", "link", "name", "cpf", "email"],
  loading: ["loading"],
  h3: ["h3"],
  span: ["span"],
  link: ["link"],
  name: ["name"],
  cpf: ["cpf"],
  email: ["email"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  loading: typeof Loading;
  h3: "h3";
  span: "span";
  link: "a";
  name: typeof TextField;
  cpf: typeof TextField;
  email: typeof TextField;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    loading: makeNodeComponent("loading"),
    h3: makeNodeComponent("h3"),
    span: makeNodeComponent("span"),
    link: makeNodeComponent("link"),
    _name: makeNodeComponent("name"),
    cpf: makeNodeComponent("cpf"),
    email: makeNodeComponent("email"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
